"""Generate paper2/results_macros.tex from the second paper's result files.

Same discipline as Paper 1: no number reaches the manuscript except through a
\result{} macro generated here, so every figure traces to the run that made it.
"""
import os, json
import numpy as np
import torch

RES = os.path.join(os.path.dirname(__file__), "..", "results")
RUNS = os.path.join(os.path.dirname(__file__), "..", "runs")
OUT = os.path.join(os.path.dirname(__file__), "..", "paper2", "results_macros.tex")
M, PROV = {}, {}


def put(k, v, src, fmt="{:.3f}"):
    M[k] = "n/a" if v is None else (v if isinstance(v, str) else fmt.format(v))
    PROV[k] = src


def load(n):
    p = os.path.join(RES, f"{n}.json")
    return json.load(open(p)) if os.path.exists(p) else None


# ---- joint training against the frozen baseline
for name, tag in (("attn_8L256_s0", "Base"), ("scr01_8L256_s0", "JointLow"),
                  ("scr05_8L256_s0", "JointHigh")):
    p = os.path.join(RUNS, f"{name}.pt")
    if os.path.exists(p):
        c = torch.load(p, map_location="cpu", weights_only=False)
        put(f"val{tag}", c["log"][-1]["val"], f"runs/{name}.pt", "{:.4f}")
        if c["log"][-1].get("scr_acc"):
            put(f"consAcc{tag}", c["log"][-1]["scr_acc"], f"runs/{name}.pt")

# ---- the fitted operators
for suf, tag in (("_trans", "One"), ("_trans12", "Multi")):
    p = os.path.join(RUNS, f"attn_8L256_s0{suf}.pt")
    if os.path.exists(p):
        c = torch.load(p, map_location="cpu", weights_only=False)
        put(f"opAcc{tag}", c["log"][-1]["acc"], f"runs/attn_8L256_s0{suf}.pt")
        put(f"opLoss{tag}", c["log"][-1]["loss"], f"runs/attn_8L256_s0{suf}.pt")

# ---- rollout quality, both operators
for suf, tag in (("_trans", "One"), ("_trans12", "Multi")):
    d = load(f"attn_8L256_s0{suf}_rollout")
    if not d:
        continue
    src = f"results/attn_8L256_s0{suf}_rollout.json"
    for key, nm in (("now", "Now"), ("rolled", "Rolled"), ("stale", "Stale")):
        v = d["occ_acc"][key]
        put(f"roll{nm}First{tag}", v[0], src)
        put(f"roll{nm}Last{tag}", v[-1], src)
    put(f"deltaFrac{tag}", d["delta_over_hidden"][0], src)

# ---- the repair experiment
d = load("attn_8L256_s0_refresh")
if d:
    src = "results/attn_8L256_s0_refresh.json"
    put("repairN", int(sum(d["n"])), src, "{:,.0f}")
    for m in ("noop", "repair", "stale", "random"):
        put(f"rep{m.capitalize()}Mid", d["illegal"][m][2], src)
        put(f"rep{m.capitalize()}Deep", d["illegal"][m][-1], src)

# ---- drift detection
d = load("attn_8L256_s0_drift_detect")
if d:
    src = "results/attn_8L256_s0_drift_detect.json"
    put("detN", d["n"], src, "{:,.0f}")
    put("detGames", d["n_games"], src, "{:,.0f}")
    put("detBase", d["base_rate"], src)
    for k, nm in (("model_confidence", "Conf"), ("consistency_error", "Cons")):
        v = d["auc"][k]
        put(f"aucDet{nm}", v["auc"], src, "{:.4f}")
        put(f"aucDet{nm}Lo", v["ci_lo"], src, "{:.4f}")
        put(f"aucDet{nm}Hi", v["ci_hi"], src, "{:.4f}")
    c = d["combined"]
    put("aucHoConf", c["auc_conf_heldout"], src, "{:.4f}")
    put("aucHoCons", c["auc_cons_heldout"], src, "{:.4f}")
    put("aucHoComb", c["auc_heldout"], src, "{:.4f}")
    put("betaDetConf", c["beta_confidence"], src, "{:+.3f}")
    put("betaDetCons", c["beta_consistency"], src, "{:+.3f}")
    for cov in ("0.5", "0.7"):
        t = cov.replace(".", "")
        for k, nm in (("model_confidence", "Conf"), ("consistency_error", "Cons"),
                      ("combined", "Comb")):
            put(f"cov{nm}{t}", d["coverage"][cov][k], src, "{:.4f}")

# ---- carried over from Paper 1, for continuity
d = load("attn_8L256_s0_belief")
if d and "clustered" in d:
    c = d["clustered"]; src = "results/attn_8L256_s0_belief.json"
    put("p1Belief", c["own"]["mean"], src)
    put("p1BeliefMis", c["mis"]["mean"], src)
d = load("attn_8L256_s0")
if d:
    src = "results/attn_8L256_s0.json"
    bl = d["best_layer"]
    put("p1OccFirst", np.array(d["fidelity_occ"])[bl][0], src)
    put("p1OccLast", np.array(d["fidelity_occ"])[bl][-1], src)
    put("p1IllFirst", d["illegal"][0], src, "{:.4f}")
    put("p1IllLast", d["illegal"][-1], src)


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    L = ["% AUTO-GENERATED by code/make_macros2.py. Do not edit by hand.",
         r"\makeatletter",
         r"\newcommand{\result}[1]{%",
         r"  \expandafter\ifx\csname result@#1\endcsname\relax",
         r"    \textbf{??}\PackageWarning{results}{undefined key: #1}%",
         r"  \else\csname result@#1\endcsname\fi}",
         r"\newcommand{\defresult}[2]{\expandafter\def\csname result@#1\endcsname{#2}}",
         r"\makeatother", ""]
    for k in sorted(M):
        L.append(f"\\defresult{{{k}}}{{{M[k]}}}   % {PROV[k]}")
    open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    json.dump({k: {"value": M[k], "source": PROV[k]} for k in M},
              open(os.path.join(RES, "macro_provenance2.json"), "w"), indent=1)
    print(f"wrote {OUT}: {len(M)} keys")


if __name__ == "__main__":
    main()
