"""Convert the Coherent Errors manuscript to the JAIR submission format.

JAIR rejects submissions not in its format without review, and desk rejects
submissions without a completed reproducibility checklist, so neither is
optional. Since spring 2025 the required style is jair.cls, built on ACM's
acmart, with biblatex and biber rather than natbib.

This is a conversion script rather than a hand edit because the body of the
manuscript still lives in paper/main.tex and will keep changing. Running the
conversion each time keeps the JAIR copy from drifting away from the source, in
the way this project has repeatedly found things drift once a derived artifact
is edited by hand.

What it changes, and nothing else: the document class and preamble, the author
block, the citation commands, and the appended checklist. The body text is taken
verbatim.
"""
from __future__ import annotations

import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "paper", "main.tex")
OUT = os.path.join(ROOT, "paper_jair", "main.tex")
B = chr(92)

PREAMBLE = r"""%% Coherent Errors, formatted for the Journal of Artificial Intelligence
%% Research. Generated by code/make_jair.py from paper/main.tex; edit the source,
%% not this file.
\documentclass[manuscript, screen, review]{jair}

\setcopyright{cc}
\acmDOI{10.1613/jair.1.xxxxx}

\JAIRAE{}
\JAIRTrack{}

\RequirePackage[
  datamodel=acmdatamodel,
  style=acmauthoryear,
  backend=biber,
  giveninits=true,
  uniquename=init
  ]{biblatex}
\renewcommand*{\bibopenbracket}{(}
\renewcommand*{\bibclosebracket}{)}
\addbibresource{refs.bib}

%% The manuscript was written against natbib. biblatex's acmauthoryear style
%% already provides \citep and \citet, so nothing is aliased here; defining them
%% again is an error rather than a convenience. acmart likewise already loads
%% amsmath and amssymb, so only the packages it does not provide are requested.
\usepackage{booktabs,graphicx,array,enumitem}
\graphicspath{{figures/}}
\input{results_macros.tex}   % measured values only

\newtheorem{jairdefinition}{Definition}
\newtheorem{jairproposition}{Proposition}
\theoremstyle{remark}
\newtheorem{jairremark}{Remark}
\newenvironment{definition}{\begin{jairdefinition}}{\end{jairdefinition}}
\newenvironment{proposition}{\begin{jairproposition}}{\end{jairproposition}}
\newenvironment{remark}{\begin{jairremark}}{\end{jairremark}}

%% JAIR reviewing is single anonymous: reviewers are anonymous to authors, and
%% authors are named. The toggle is kept so the anonymous build still exists for
%% other venues, and defaults to naming the authors.
\newif\ifanon
\ifdefined\ANON\anontrue\else\anonfalse\fi

\begin{document}

\title[Coherent Errors]{Coherent Errors: Chess Transformers Act on
Misremembered Boards}

\author{Mohit Pratap Singh Rathore}
\authornote{Corresponding author.}
\email{mohitpratapsinghr@gmail.com}
\affiliation{%
  \institution{Oviqo}
  \country{India}
}

\author{Gunveer Singh Kalsi}
\email{gunveerkalsi@gmail.com}
\affiliation{%
  \institution{Oviqo}
  \country{India}
}

\author{Sriharsha Meduri}
\email{sriharshameduri07@gmail.com}
\affiliation{%
  \institution{Oviqo}
  \country{India}
}

\author{Pratap Chandra Mandal}
\affiliation{%
  \institution{Indian Institute of Management Shillong}
  \country{India}
}

\renewcommand{\shortauthors}{Rathore, Kalsi, Meduri \& Mandal}
"""


def structured_abstract(body: str) -> str:
    """Return the source abstract and a structured replacement for it.

    JAIR encourages structured abstracts. The sections are written out rather
    than inferred from paragraph order, because the source abstract's second
    paragraph is results, not objectives, and an automatic labeller mislabels
    it. The wording is the source's own and every measured value is still a
    \\result macro, so the abstract cannot drift from the result files.

    The guard matters more than the convenience: if the source abstract is
    edited so that these phrases no longer appear, this raises instead of
    emitting a structured abstract that has quietly stopped matching the paper.
    """
    m = re.search(r"\\begin{abstract}(.*?)\\end{abstract}", body, re.S)
    if not m:
        raise SystemExit("no abstract found in the source")
    src = " ".join(m.group(1).split())          # unwrap before matching
    required = [
        "confounds two failures with opposite remedies",
        "Aggregate state fidelity",
        "are legal there",
        "norm-matched random edit",
        "We report failures too",
    ]
    missing = [r for r in required if r not in src]
    if missing:
        raise SystemExit(
            "the source abstract has changed; the structured version in "
            "code/make_jair.py must be rewritten to match. Missing: "
            + "; ".join(missing))

    def M(name):
        return "\\result{" + name + "}"

    parts = [
        ("Background:",
         "Long-horizon failure is reported as one number, which confounds two "
         "failures with opposite remedies: the model has lost track of the "
         "world, or it holds the world and chooses badly."),
        ("Objectives:",
         "We separate the two, and ask the further question a separation alone "
         "leaves open: whether the internal state a probe recovers is merely "
         "present or is actually read by the policy that acts."),
        ("Methods:",
         "We work where an exact state oracle exists, chess from move notation "
         "with no search at inference, in models of " + M("paramsSmall") +
         " to " + M("paramsLarge") + " parameters, reading linear probes "
         "against the true position at every token. Errors are scored against "
         "the board the model appears to believe, with same-depth "
         "mismatched-belief and random-move controls, and the representation "
         "is edited at a calibrated strength against a norm-matched random "
         "direction."),
        ("Results:",
         "Aggregate state fidelity, the quantity usually reported, is the "
         "weaker predictor of an illegal next move within a fixed depth, at "
         "AUC " + M("aucAggMin") + " to " + M("aucAggMax") + " against " +
         M("aucActMin") + " to " + M("aucActMax") + " for the same "
         "representation restricted to the squares the move touches. And the "
         "errors are coherent. Reconstructing the position the model appears "
         "to believe, " + M("belIllAttn") + " of its illegal moves are legal "
         "there, against " + M("belMisAttn") + " for the same move under "
         "another position's belief and " + M("belRandAttn") + " for an "
         "arbitrary illegal move. Editing the probe direction encoding an "
         "occupied square removes " + M("patchCutAttn") + " of the probability "
         "mass on moves from it, a norm-matched random edit " +
         M("patchRandCutAttn") + ", so the representation is read and not "
         "merely present. Belief consistency rises monotonically across six "
         "model sizes, though the causal edit is not measured at every size."),
        ("Conclusions:",
         "A substantial identified subset of long-horizon error is coherent "
         "with a degraded state the policy demonstrably reads. The practical "
         "consequence is a change in what to measure: a world model reported "
         "as an aggregate accuracy tells less than the same representation "
         "scored on the state the next action will consume. We report failures "
         "too: a backwards layer profile, a degenerate pre-registered metric, "
         "an auxiliary objective improving the measurement of state more than "
         "its consequences, and a second domain needing seven designs to "
         "become measurable."),
    ]
    out = ["\\begin{abstract}"]
    for lab, text in parts:
        out.append("{\\bf " + lab + "}" + chr(10) + text + chr(10))
    out.append("\\end{abstract}")
    return m.group(0), chr(10).join(out)


CHECKLIST = r"""
\appendix

\section{Reproducibility Checklist for JAIR}

Select the answers that apply to your research -- one per item.

\subsection*{All articles:}
\begin{enumerate}
    \item All claims investigated in this work are clearly stated. \textbf{yes}
    \item Clear explanations are given how the work reported substantiates the
    claims. \textbf{yes}
    \item Limitations or technical assumptions are stated clearly and
    explicitly. \textbf{yes}
    \item Conceptual outlines and/or pseudo-code descriptions of the AI methods
    introduced in this work are provided, and important implementation details
    are discussed. \textbf{yes}
    \item Motivation is provided for all design choices, including algorithms,
    implementation choices, parameters, data sets and experimental protocols
    beyond metrics. \textbf{yes}
\end{enumerate}

\subsection*{Articles containing theoretical contributions:}
Does this paper make theoretical contributions? \textbf{no}

\subsection*{Articles reporting on computational experiments:}
Does this paper include computational experiments? \textbf{yes}

\begin{enumerate}
    \item All source code required for conducting experiments is included in an
    online appendix or will be made publicly available upon publication of the
    paper. The online appendix follows best practices for source code
    readability and documentation as well as for long-term accessibility.
    \textbf{yes}
    \item The source code comes with a license that allows free usage for
    reproducibility purposes. \textbf{yes}
    \item The source code comes with a license that allows free usage for
    research purposes in general. \textbf{yes}
    \item Raw, unaggregated data from all experiments is included in an online
    appendix or will be made publicly available upon publication of the paper.
    The online appendix follows best practices for long-term accessibility.
    \textbf{partially}
    \item The unaggregated data comes with a license that allows free usage for
    reproducibility purposes. \textbf{yes}
    \item The unaggregated data comes with a license that allows free usage for
    research purposes in general. \textbf{yes}
    \item If an algorithm depends on randomness, then the method used for
    generating random numbers and for setting seeds is described in a way
    sufficient to allow replication of results. \textbf{yes}
    \item The execution environment for experiments, the computing
    infrastructure (hardware and software) used for running them, is described,
    including GPU/CPU makes and models; amount of memory (cache and RAM); make
    and version of operating system; names and versions of relevant software
    libraries and frameworks. \textbf{yes}
    \item The evaluation metrics used in experiments are clearly explained and
    their choice is explicitly motivated. \textbf{yes}
    \item The number of algorithm runs used to compute each result is reported.
    \textbf{yes}
    \item Reported results have not been ``cherry-picked'' by silently ignoring
    unsuccessful or unsatisfactory experiments. \textbf{yes}
    \item Analysis of results goes beyond single-dimensional summaries of
    performance (e.g., average, median) to include measures of variation,
    confidence, or other distributional information. \textbf{yes}
    \item All (hyper-) parameter settings for the algorithms/methods used in
    experiments have been reported, along with the rationale or method for
    determining them. \textbf{yes}
    \item The number and range of (hyper-) parameter settings explored prior to
    conducting final experiments have been indicated, along with the effort
    spent on (hyper-) parameter optimisation. \textbf{partially}
    \item Appropriately chosen statistical hypothesis tests are used to
    establish statistical significance in the presence of noise effects.
    \textbf{yes}
\end{enumerate}

\subsection*{Articles using data sets:}
Does this work rely on one or more data sets? \textbf{yes}

\begin{enumerate}
    \item All newly introduced data sets are included in an online appendix or
    will be made publicly available upon publication of the paper. The online
    appendix follows best practices for long-term accessibility with a license
    that allows free usage for research purposes. \textbf{NA}
    \item The newly introduced data set comes with a license that allows free
    usage for reproducibility purposes. \textbf{NA}
    \item The newly introduced data set comes with a license that allows free
    usage for research purposes in general. \textbf{NA}
    \item All data sets drawn from the literature or other public sources
    (potentially including authors' own previously published work) are
    accompanied by appropriate citations. \textbf{yes}
    \item All data sets drawn from the existing literature (potentially
    including authors' own previously published work) are publicly available.
    \textbf{yes}
    \item All new data sets and data sets that are not publicly available are
    described in detail, including relevant statistics, the data collection
    process and annotation process if relevant. \textbf{yes}
    \item All methods used for preprocessing, augmenting, batching or splitting
    data sets (e.g., in the context of hold-out or cross-validation) are
    described in detail. \textbf{yes}
\end{enumerate}

\subsection*{Explanations on any of the answers above (optional):}

No new data set is introduced: the corpus is a public game archive filtered by
rating and deduplicated, and the filtering and splitting are described in
Section~5. Raw unaggregated data is marked \emph{partially} because the
per-position activation tensors are too large to host, while the per-position
measurements derived from them, which are what every reported number is computed
from, are released in full alongside the code. Trained checkpoints are available
from the corresponding author on request for the same reason. The
hyper-parameter item is marked \emph{partially} because the model and training
settings were fixed from standard practice rather than tuned, so there was no
search whose range we could report; the one quantity that was calibrated, the
intervention edit strength, is reported with its full sweep in Section~6.6.
"""


def main() -> int:
    src = io.open(SRC, encoding="utf-8").read()
    body = src.split(r"\begin{document}", 1)[1]
    body = body.split(r"\end{document}")[0]
    # The source's own title and maketitle are replaced by the JAIR preamble's.
    body = re.sub(r"\\maketitle\s*", "", body, count=1)

    # acmart requires the abstract before \maketitle, so it is lifted out of the
    # body rather than left where the article class allowed it to sit.
    old_abs, new_abs = structured_abstract(body)
    body = body.replace(old_abs, "", 1)

    # biblatex prints the bibliography; natbib's command is replaced.
    body = re.sub(r"\\bibliographystyle\{[^}]*\}\s*", "", body)
    body = re.sub(r"\\bibliography\{[^}]*\}", r"\\printbibliography", body)
    if r"\printbibliography" not in body:
        body += "\n" + r"\printbibliography" + "\n"

    out = (PREAMBLE + "\n" + new_abs + "\n\n\\maketitle\n" + body
           + CHECKLIST + "\n\\end{document}\n")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(out)
    n_cite = len(re.findall(r"\\cite[pt]?\{", out))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(out.splitlines())} lines, "
          f"{n_cite} citations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
