"""Do the findings survive off-distribution, on uniformly random legal play?

Every measurement so far uses held-out human games. Those are in-distribution,
and \citet{walker2026chess} report that a uniformly-random-legal-play split stays
discriminative at sizes where in-distribution performance has saturated. If our
findings are partly an artifact of familiar opening theory and typical middlegame
structure, random play should weaken them.

Random trajectories are generated by sampling uniformly among legal moves, so the
positions are legal but the move distribution is nothing like training. We report
the same quantities: probe fidelity against depth, illegal top-1 rate, and belief
consistency with its controls.
"""
import os, json, argparse
import numpy as np
import torch
import chess
from probes import build

DATA = os.path.join(os.path.dirname(__file__), "..", "data", "proc")
RUNS = os.path.join(os.path.dirname(__file__), "..", "runs")
RES = os.path.join(os.path.dirname(__file__), "..", "results")
BUCKETS = [(0, 10), (10, 20), (20, 30), (30, 40), (40, 50),
           (50, 60), (60, 80), (80, 120)]

CLS2PIECE = {}
for ci, col in enumerate([chess.WHITE, chess.BLACK]):
    for pi, pt in enumerate([chess.PAWN, chess.KNIGHT, chess.BISHOP,
                             chess.ROOK, chess.QUEEN, chess.KING]):
        CLS2PIECE[1 + ci * 6 + pi] = (pt, col)
PIECE2CLS = {v: k for k, v in CLS2PIECE.items()}


def gen_random_games(n, stoi, max_ply=120, seed=0):
    """Uniform random legal play. Returns token ids, lengths, per-ply occupancy."""
    rng = np.random.default_rng(seed)
    L = max_ply + 1
    toks = np.zeros((n, L), dtype=np.int64)
    occ = np.zeros((n, L, 64), dtype=np.uint8)
    lens = np.zeros(n, dtype=np.int64)
    kept = 0
    while kept < n:
        b = chess.Board()
        seq = [stoi["<bos>"]]
        occs = []
        for t in range(max_ply):
            occs.append([PIECE2CLS[(p.piece_type, p.color)] if p else 0
                         for p in (b.piece_at(q) for q in range(64))])
            if b.is_game_over():
                break
            legal = list(b.legal_moves)
            mv = legal[int(rng.integers(len(legal)))]
            if mv.uci() not in stoi:
                break
            seq.append(stoi[mv.uci()])
            b.push(mv)
        if len(seq) < 25:
            continue
        n_t = min(len(seq), L)
        toks[kept, :n_t] = seq[:n_t]
        occ[kept, :len(occs)] = np.array(occs, dtype=np.uint8)[:L]
        lens[kept] = n_t
        kept += 1
    return toks, lens, occ


def believed_board(row, turn_white):
    b = chess.Board(None)
    for sq in range(64):
        c = int(row[sq])
        if c:
            pt, col = CLS2PIECE[c]
            b.set_piece_at(sq, chess.Piece(pt, col))
    b.turn = chess.WHITE if turn_white else chess.BLACK
    b.castling_rights = 0
    return b


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", default="attn_8L256_s0")
    ap.add_argument("--games", type=int, default=1200)
    args = ap.parse_args()

    model, a, c = build(os.path.join(RUNS, f"{args.name}.pt"))
    res = json.load(open(os.path.join(RES, f"{args.name}.json")))
    best = res["best_layer"]
    pls = torch.load(os.path.join(RES, f"{args.name}_probes.pt"), weights_only=False)
    probe = torch.nn.Linear(a["width"], 64 * 13).cuda()
    probe.load_state_dict(pls[best]); probe.eval()

    stoi = json.load(open(os.path.join(DATA, "vocab.json")))
    itos = {v: k for k, v in stoi.items()}
    print("generating random legal play", flush=True)
    toks, lens, occ = gen_random_games(args.games, stoi)

    nb = len(BUCKETS)
    occ_hit = np.zeros(nb); occ_n = np.zeros(nb)
    ill = np.zeros(nb); tot = np.zeros(nb)
    bel_hit = 0.0; bel_n = 0.0; rnd_hit = 0.0; rnd_n = 0.0
    all_moves = [m for m in stoi if m not in ("<pad>", "<bos>")]
    rng = np.random.default_rng(0)

    with torch.no_grad():
        for i in range(0, len(toks), 32):
            idx = np.arange(i, min(i + 32, len(toks)))
            x = torch.from_numpy(toks[idx]).cuda()
            s = torch.from_numpy(occ[idx].astype(np.int64)).cuda()
            with torch.amp.autocast("cuda", dtype=torch.float16):
                logits, hs, _ = model(x[:, :-1], return_hidden=True)
            pred = logits.float().argmax(-1).cpu().numpy()
            dec = probe(hs[best].float()).reshape(len(idx), -1, 64, 13).argmax(-1)
            ok = (dec == s[:, :dec.shape[1]]).cpu().numpy()
            decn = dec.cpu().numpy()
            for r, gi in enumerate(idx):
                board = chess.Board()
                T = int(lens[gi])
                for t in range(min(T - 1, ok.shape[1])):
                    bi = next((k for k, (lo, hi) in enumerate(BUCKETS)
                               if lo <= t < hi), None)
                    if bi is not None:
                        occupied = occ[gi, t] > 0
                        if occupied.sum():
                            occ_hit[bi] += float((ok[r, t] & occupied).sum())
                            occ_n[bi] += float(occupied.sum())
                        mv = itos.get(int(pred[r, t]), "")
                        try:
                            m_ = chess.Move.from_uci(mv)
                            legal = m_ in board.legal_moves
                        except Exception:
                            m_, legal = None, False
                        tot[bi] += 1
                        ill[bi] += (not legal)
                        if m_ is not None and not legal:
                            bb = believed_board(decn[r, t], board.turn == chess.WHITE)
                            bel_n += 1
                            bel_hit += (m_ in bb.pseudo_legal_moves)
                            for _ in range(6):
                                cand = chess.Move.from_uci(
                                    all_moves[int(rng.integers(len(all_moves)))])
                                if cand not in board.legal_moves:
                                    rnd_n += 1
                                    rnd_hit += (cand in bb.pseudo_legal_moves)
                                    break
                    board.push_uci(itos[int(toks[gi, t + 1])])

    out = {"name": args.name, "n_games": int(len(toks)), "buckets": BUCKETS,
           "occ_acc": (occ_hit / np.maximum(occ_n, 1)).tolist(),
           "illegal": (ill / np.maximum(tot, 1)).tolist(),
           "belief_consistency": float(bel_hit / max(bel_n, 1)),
           "belief_n": int(bel_n),
           "random_move_control": float(rnd_hit / max(rnd_n, 1))}
    json.dump(out, open(os.path.join(RES, f"{args.name}_randomplay.json"), "w"),
              indent=1)
    print(f"[{args.name}] uniformly random legal play, {len(toks)} games")
    print(f"{'ply':>9} {'occ acc':>9} {'illegal':>9}")
    for i, (lo, hi) in enumerate(BUCKETS):
        if tot[i]:
            print(f"{str(lo)+'-'+str(hi):>9} {out['occ_acc'][i]:9.3f} "
                  f"{out['illegal'][i]:9.3f}")
    print(f"belief consistency {out['belief_consistency']:.3f} "
          f"(n={int(bel_n)}), random-move control {out['random_move_control']:.3f}")


if __name__ == "__main__":
    main()
